format = """$directory${custom.die_success}${custom.die_error}${custom.die_vim} """
palette = "catppuccin_mocha"
right_format = """
$git_branch\
$git_commit\
$git_state\
$git_status\
\
$bun\
$c\
$cpp\
$elixir\
$elm\
$deno\
$gleam\
$golang\
$java\
$lua\
$nodejs\
$python\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$typst\
$zig\
\
$cmd_duration\
"""

# Unused for now
# $aws\
# $gcloud\
# $azure\
# $nix_shell\
# $docker_context\

[custom.die_success]
command = '''
chars=('󰇊' '󰇋' '󰇌' '󰇍' '󰇎' '󰇏')
randomindex=$(( RANDOM % 6 + 1 ))
echo ${chars[$randomindex]}
'''
when = '[ "$VIM_MODE" = "insert" ] && [ -n "$LAST_CMD_OK" ]'
format = '[$output](green)'
shell = ["zsh"]

[custom.die_error]
command = '''
chars=('󰇊' '󰇋' '󰇌' '󰇍' '󰇎' '󰇏')
randomindex=$(( RANDOM % 6 + 1 ))
echo ${chars[$randomindex]}
'''
when = '[ "$VIM_MODE" = "insert" ] && [ -z "$LAST_CMD_OK" ]'
format = '[$output](red)'
shell = ["zsh"]

[custom.die_vim]
command = '''
chars=('󰇊' '󰇋' '󰇌' '󰇍' '󰇎' '󰇏')
randomindex=$(( RANDOM % 6 + 1 ))
echo ${chars[$randomindex]}
'''
when = '[ "$VIM_MODE" = "normal" ]'
format = '[$output](yellow)'
shell = ["zsh"]

[directory]
style = "blue"

[git_branch]
symbol = ""
format = '[ $symbol $branch]($style)'
style = "lavender"

[git_status]
format = '[( $all_status$ahead_behind)]($style)'
style = "lavender"

[git_commit]

[git_state]

[cmd_duration]
format = '[ $duration]($style)'
style = "yellow"

# Languages

[bun]
symbol = ""
format = '[ $symbol( $version)]($style)'
style = "lavender"

[c]
symbol = ""
format = '[ $symbol( $version)]($style)'
style = "lavender"

[cpp]
symbol = ""
format = '[ $symbol( $version)]($style)'
style = "lavender"

[elixir]
symbol = ""
format = '[ $symbol( $version)]($style)'
style = "lavender"

[elm]
symbol = ""
format = '[ $symbol( $version)]($style)'
style = "lavender"

[deno]
symbol = ""
format = '[ $symbol( $version)]($style)'
style = "lavender"

[gleam]
symbol = ""
format = '[ $symbol( $version)]($style)'
style = "lavender"

[golang]
symbol = ""
format = '[ $symbol( $version)]($style)'
style = "lavender"

[java]
symbol = ""
format = '[ $symbol( $version)]($style)'
style = "lavender"

[lua]
symbol = "󰢱"
format = '[ $symbol( $version)]($style)'
style = "lavender"

[nodejs]
symbol = ""
format = '[ $symbol( $version)]($style)'
style = "lavender"

[python]
symbol = "󰌠"
format = '[ $symbol( $version)]($style)'
style = "lavender"

[ruby]
symbol = "󰴭"
format = '[ $symbol( $version)]($style)'
style = "lavender"

[rust]
symbol = "󱘗"
format = '[ $symbol( $version)]($style)'
style = "lavender"

[scala]
symbol = ""
format = '[ $symbol( $version)]($style)'
style = "lavender"

[swift]
symbol = "󰛥"
format = '[ $symbol( $version)]($style)'
style = "lavender"

[terraform]
symbol = "󱁢"
format = '[ $symbol( $version)]($style)'
style = "lavender"

[typst]
symbol = ""
format = '[ $symbol( $version)]($style)'
style = "lavender"

[zig]
symbol = ""
format = '[ $symbol( $version)]($style)'
style = "lavender"

# Theme

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
